### ISSUE TITLE
Create an outfit switch system so that changing clothing context doesn't require an avatar reload

### ISSUE THREAD

**Issue by fire** [V-Sekai/manuals#443]
### Metadata

- Status: proposed 
- Deciders: V-Sekai,fire,lyuma,
- Tags: V-Sekai,

### Context and Problem Statement

Lyuma wants to hop into a swimming pool and switch to a swimsuit or dance and turn off the garment in the way.

### Describe the proposed option and how it helps to overcome the problem or limitation

Allow the player to toggle off the body with alpha layers and turn on the garment.

Able to have one avatar with multiple outfits but efficiently on the device.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, or diagrams

Use 3 bitmasks which are 8 bit. Avoid RGBAH because of complexity. 

We have 3 rgb color channels, so we can do up to 24*3 with 8bit. 

This means we can have 72 arbitrary alpha layers per material.

Be able to animate the switch, not simply toggle in a single frame.

Apply the alpha layers by using the NAN floating point trick on the mesh vertices to discard them.

For ease of use, we will create an animation that has a 0 to 1 in discrete mode that changes the panel combinations.

### Positive Consequences

Without a reload we can switch clothing without clipping the skin.

Efficient.

### Negative Consequences

We cannot get other features in.

### Option graveyard

- Option: The status quo. 
- Rejection Reason: This solves nothing. 

- Option: scale individual meshes to 0 and toggle them on and off using animations.
- Rejection Reason: bad performance

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Knowing what to do is hard.

### Is there a reason why this should be core and done by us?

Usability is a core feature. So is performance.

### References

- [V-Sekai](https://v-sekai.org/)
- https://twitter.com/lil_xyzw/status/1625774216502198272
- https://booth.pm/ja/items/1894974

**Comment by fire** [comment]
Silent's Cel Shading Shader has 16 inventory slots and almost does this.

**Comment by fire** [comment]
The https://cafemohka.booth.pm/items/4265391 model is already setup for the uv trick. Will try the SCSS inventory.

**Comment by fire** [comment]
1. Move the meshes in this pattern for organizerion.
  2. base mesh, garment 1, garment 2, garment 3, base mesh (skin only)
3. Move the uvs by adding the x value to the base mesh
4. Duplicate the textures as many number of inventory items. to the right

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/220246404-dc4e2119-6328-4d07-8664-30e583d59c64.png)

Sort by uv distance = x + uv 
and y for each texture
to conserve UDIM texture space

**Comment by fire** [comment]
Sort by uv distance = x + uv
and y for each texture
to conserve UDIM texture space

**Comment by fire** [comment]
Use the names to layout a hierachy `Mire.Ms.Garments`.

**Comment by fire** [comment]
Blender only allows 0 to 10 uv coordinates..

**Comment by lyuma** [comment]
I would recommend against using Blender's UDIM tile system since each of these tiles use the same texture.

As for the distance between tiles, it is assigned in `_InventoryStride`, so it is posible to permit spacing them further than 1 if tiling is needed.

In a conventional blender UV map, it is sufficient to move polygons by integer offsets of any amount. The 10 limit is only when using Blender's  UDIM tile system.

That said, if you want to use more, you can always change the shader to use `in_texcoord.y` instead of `in_texcoord.x` and then you can have unlimited vertical tiles in Blender.

**Comment by fire** [comment]
People aren't opening the application. There is an advanced features for advanced users. Will work on the core features first.
